# Fun little hack for checking what OS we're in.
# This is only for copying text to the system clipboard
#   Windows   = 0
#   UNIX      = 1
#   MacOS     = 2
run-shell 'tmux setenv -g UNIX_VER $(grep -q "[Mm]icrosoft" /proc/version; echo $?)'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Theme
set -g @plugin 'dracula/tmux'
set -g @dracula-show-battery false
set -g @dracula-show-network false
set -g @dracula-show-weather false
set -g @dracula-show-powerline true
set -g @dracula-cpu-usage true
set -g @dracula-ram-usage true
set -g @dracula-show-timezone false
set -g @dracula-show-left-icon session

# Switch panes using Alt+ArrowKeys without the prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable the new mouse mode for clicking between panes
set -g mouse on

# Search with VI
set-window-option -g mode-keys vi

# Copy text to clipboard on highlight
#   UNIX will use xclip
#   WSL will use clip.exe
#   Max will use pbcopy
set-option -s set-clipboard off
if-shell -b '[ "$UNIX_VER" = 0 ]' " \
  bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'clip.exe'"
if-shell -b '[ "$UNIX_VER" = 1 ]' " \
  bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -se c -i'"
if-shell -b '[ "$UNIX_VER" = 2 ]' " \
  bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'"

# Easer Pane splitting (and with same working directory)
bind _ split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# Misc changes
set-option -g history-limit 102400
set-option -g allow-rename off

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
