#!/usr/bin/env bash
set -uo pipefail

PROJECTS_DIR="$HOME/GitHub"
PROJECT=$(
    find "$PROJECTS_DIR" -type d \
        -maxdepth 3 \
        -exec test -e "{}/.git" \; \
        -print \
        -prune |
    sort -u |
    fzf --prompt="Project> "
)
RC=$?

if [ "$RC" -eq 0 ] && [ -n "$PROJECT" ]; then
  zeditor -e "$PROJECT"
fi
exit 0
